/* CRIANDO TABELA CATEGORIAS */
CREATE TABLE categorias (id BIGINT NOT NULL AUTO_INCREMENT, nome VARCHAR(100), PRIMARY KEY (id));  

/* CRIANDO TABELA PRODUTOS */
CREATE TABLE produtos (id BIGINT NOT NULL AUTO_INCREMENT, nome VARCHAR(255), preco DECIMAL(10,2), categoria_id BIGINT, PRIMARY KEY (id), FOREIGN KEY (categoria_id) REFERENCES categorias(id));

/* CRIANDO TABELA CLIENTES */
CREATE TABLE clientes (id BIGINT NOT NULL AUTO_INCREMENT, nome VARCHAR(255), PRIMARY KEY (id));

/* CRIANDO TABELA PEDIDOS */
CREATE TABLE pedidos (id BIGINT NOT NULL AUTO_INCREMENT, data DATETIME, cliente_id BIGINT, PRIMARY KEY (id), FOREIGN KEY (cliente_id) REFERENCES clientes(id));

/* CRIANDO TABELA ITEM_PEDIDO */
CREATE TABLE item_pedido (id BIGINT NOT NULL AUTO_INCREMENT, pedido_id BIGINT, produto_id BIGINT, preco_unitario DECIMAL(10,2), quantidade INTEGER, PRIMARY KEY (id), FOREIGN KEY (pedido_id) REFERENCES pedidos(id), FOREIGN KEY (produto_id) REFERENCES produtos(id));
